[build-system]
requires = [
    "py-cord>=2.7.1",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "corpoch"
version = "1.7.0-beta.1"
description = "Corpo CH Tournament Bot"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
authors = [
    { name = "Connor Meade", email = "crmeade@mtu.edu"}
]
keywords = [
    "clonehero",
    "tournament",
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["corpoch*"]

[tool.flit.module]
name = "corpoch"

[tool.isort]
profile = "django"
skip_gitignore = true
